<a href="https://colab.research.google.com/github/adtitovich/numpy-38/blob/main/m1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Домашнее задание «Библиотека numpy. Вычислительные задачи»***

**Задание 1**

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [27]:
import numpy as np

n = 10

array = np.arange(n-1, -1, -1)
print(array)

[9 8 7 6 5 4 3 2 1 0]


**Задание 2**

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [28]:
import numpy as np

n = 10

# диагональная матрица
m = np.diag(np.arange(n-1, -1, -1))
print(m)

# Так как матрица диагональная, то сумма значений на диагонали = сумма значений всех элементов матрицы
print(f'Сумма значений на диагонали: {m.sum()}')

[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
Сумма значений на диагонали: 45


**Задание 3**

Решите систему уравнений:
```
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3
```

In [29]:
import numpy as np
from numpy import linalg

#коэффициенты при переменных
a = np.array([ [4, 2, 1], [1, 3, 0], [0, 5, 4] ])

# коэффициенты правой части
b = np.array([4, 12, -3])

# решаем
s = linalg.solve(a,b)

print(f'x = {s[0]}, y = {s[1]}, z = {s[2]}')

x = 0.4666666666666668, y = 3.844444444444444, z = -5.555555555555555


**Задание 4**

Задание находится в тренажере “Косинусное сходство”

Имеется матрица покупок в интернет-магазине - users_stats. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем

На сайт заходит очередной посетитель, о покупках которого известно следующее:
next_user_stats

Найдите индекс самого похожего пользователя max_index.
Нумерацию индексов следует начинать с 0

In [31]:
import numpy as np
from numpy.linalg import norm

users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
)
#косинус угла между пользователями
cosine = np.dot(users_stats, next_user_stats)/(norm(users_stats, axis=1)*norm(next_user_stats))

# индекс самого похожего пользователя 
max_index = np.argmax(cosine)

print(f'Индекс самого похожего пользователя - {max_index}')


Индекс самого похожего пользователя - 7
