<a href="https://colab.research.google.com/github/adtitovich/numpy-38/blob/main/m1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Домашнее задание «Библиотека numpy. Вычислительные задачи»***

**Задание 1**

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [7]:
import numpy as np

n = 10
array = np.arange(n-1, -1, -1)
print(array)

[9 8 7 6 5 4 3 2 1 0]


**Задание 2**

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [12]:
import numpy as np

n = 10

m = np.diag(np.arange(n-1, -1, -1))
print(m)
# Так как матрица диагональная, то сумма значений на диагонали = сумма значений всех элементов матрицы
print(f'Сумма значений на диагонали: {m.sum()}')

[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
Сумма значений на диагонали: 45


**Задание 3**

Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

**Задание 4**

Задание находится в тренажере “Косинусное сходство”